### ISSUE TITLE
include download link or link to source

### ISSUE THREAD

**Issue by rabernat** [danielfrg/pelican-ipynb#100]
Thanks for this great package! I use it for my course website for [Research Computing in Earth Sciences](https://rabernat.github.io/research_computing_2018/).

It would be cool if it were possible to download the notebook pages _as notebooks_, via a link. Is this possible within the scope of the plugin?

**Comment by danielfrg** [comment]
Hi, yes this is supported if you use the markup mode. Check the `IPYNB_NB_SAVE_AS` setting here: `https://github.com/danielfrg/pelican-ipynb#settings`.
