### ISSUE TITLE
Unexpected keyword error when using liquid-tags mode

### ISSUE THREAD

**Issue by jreiberkyle** [danielfrg/pelican-ipynb#101]
I get the following error when I attempt to render a notebook using the liquid-tags mode:
```
ERROR: Could not process ./test_coverage.md
  | TypeError: store() got an unexpected keyword argument 'safe'
```
I don't get this error if I render the same notebook using the markdown mode.

##  Context

test_coverage.md
```
Title: A Tutorial
Date: 12/12/2012
Tags: tutorial
Author: Test
Summary: A tutorial

{% notebook calculate_coverage.ipynb %}
```

My requirements.txt:
```
pelican==3.7
jupyter         # for pelian-ipynb
nbconvert>=4.0  # for pelian-ipynb
ipython>=4.0    # for pelian-ipynb
markdown>=2.6.1 # for pelian-ipynb
```

Liquid-tags is installed by downloading `__init__.py`, `mdx_liquid_tags.py`, and `liquid_tags.py` to `plugins/liquid_tags` from the [liquid_tags directory of the plugins repo](https://github.com/getpelican/pelican-plugins/tree/master/liquid_tags).

### Setting for (successful) markdown mode
`calculate_coverage.nbdata`:
```
Title: A Tutorial 
Date: 12/12/2012
Tags: tutorial
Author: Test
Summary: A tutorial

```

**Comment by jreiberkyle** [comment]
Hmm.. further testing reveals this is a liquid-tags issue even when I try to render a notebook not using `pelican-ipynb`. Still, it would be great if someone could try this in their environment and let me know if I'm the only one running into this issue.

**Comment by danielfrg** [comment]
You can probably fix it by removing the `safe` keyword from here: https://github.com/danielfrg/pelican-ipynb/blob/a807798842d4219c296823ebcf58ca31302f033b/liquid.py#L45

You can just remove it on your downloaded version of `liquid.py`.

Maybe a new version of pelican removed that argument.

**Comment by danielfrg** [comment]
As mentioned on https://github.com/getpelican/pelican-plugins/issues/1069 markdown 3 removed that `safe` kwarg so I removed it from here.

Let me know if that fixes it.
