### ISSUE TITLE
Visible cell numbers

### ISSUE THREAD

**Issue by fabge** [danielfrg/pelican-ipynb#106]
I use the plugin to display the jupyter notebooks with Mode A Option 2. When the notebook is displayed on my website the cell numbers are shown on the left like this:

![image](https://user-images.githubusercontent.com/21140791/47641610-cac73480-db66-11e8-863b-634499135f54.png)

How do i get rid of the cell numbers?

**Comment by tdy** [comment]
You can use css, e.g.:
```css
.input_prompt {
  visibility: hidden
}
```

**Comment by danielfrg** [comment]
Yes, this is possible with just a little bit of CSS on your theme.

You can also customize with the `IPYNB_EXPORT_TEMPLATE` settings: https://github.com/danielfrg/pelican-ipynb#settings
