### ISSUE TITLE
Has the metadata file extension changed?

### ISSUE THREAD

**Issue by matthew-brett** [danielfrg/pelican-ipynb#109]
I just tried your plugin (thanks for making it).   I did try making an `.ipynb-meta` file to match my notebook, as the README has it, but continued to get:

```
ERROR: Could not process ./julia_tiobe.ipynb
  | Exception: Could not find metadata in `.nbdata` file or inside `.ipynb`
```

until I changed the file extension to `.nbdata`.  Does the README need to be updated?

**Comment by vatsaluc** [comment]
Yes, I also think that readme needs an update. It should by .nbdata instead on .ipynb-meta

**Comment by danielfrg** [comment]
Yes, the format changed to make it more consistent. I think the readme should be good now.
Thanks for the comments.
