### ISSUE TITLE
are IPython 3 notebooks supported?

### ISSUE THREAD

**Issue by zonca** [danielfrg/pelican-ipynb#25]
if not to do you have plans for supporting them in the future?

**Comment by danielfrg** [comment]
I dont think they are but i want to support them.

I'll try to find some time to work on this soon.

**Comment by danielfrg** [comment]
Hey @zonca I just tested it with an ipython notebook v3 (notebook format v4) and everything seems to be working fine. I just did an update fixing some other stuff so maybe just try the latest version.

Feel free to reopen or create another issue if you find a problem with it :)
