### ISSUE TITLE
Error converting IPython Jupyter notebook (version 3.0.0-b1)

### ISSUE THREAD

**Issue by ThunderShiviah** [danielfrg/pelican-ipynb#26]
Running my Pelican makefile returns the following error:

` ` `
ERROR: Could not process blog/testing.ipynb 
  | Unsupported nbformat version 4
` ` `

Does the plugin need to be updated for Jupyter notebooks?

**Comment by danielfrg** [comment]
The plugin should support that version maybe you need to update IPython since that message comes from IPython.

**Comment by danielfrg** [comment]
Closing since i believe this is fixed, please reopen if not.
