### ISSUE TITLE
liquid-tags like usage

### ISSUE THREAD

**Issue by FlorianWilhelm** [danielfrg/pelican-ipynb#32]
Thanks for providing this cool pelican plugin which seems to be the only Jupyter/IPython plugin that works with never versions of IPython. Have you ever considered merging this with the [liquid-style tags plugin](https://github.com/getpelican/pelican-plugins/tree/master/liquid_tags) plugin? Or to put this another way, would it be possible to use your technique of reading an ``ipynb`` file inside regular markdown article with a syntax like ``{% notebook filename.ipynb %}``? This way, it would not be necessary to provide a ``.ipynb-meta`` and the usage of your plugin would feel more natural. Or maybe there are certain technical reasons that prevent this?

**Comment by danielfrg** [comment]
This should be possible, one of the nice things about having an external file is that it forces to all the content to be in the notebook, which I understand is kinda annoying sometimes but that allows the HTML/CSS from the notebook to integrate with the theme easier so at the end it looks better. I'll try to find sometime to look at the liquid tags and see how this would be possible.

**Comment by danielfrg** [comment]
I took some code from the notebook liquid plugin and this is now possible since commit https://github.com/danielfrg/pelican-ipynb/commit/de8b205d23e59403578d04aefffe0c7b5dc2d924.

It requires some testing so if you could test it would be nice.

**Comment by FlorianWilhelm** [comment]
Thank you! On b3af1333c7ef46f045075dd4fd75eb6e700d6682, I get an error when running pelican:
```
Traceback (most recent call last):
  File "/home/fwilhelm/.virtualenvs/venv/bin/pelican", line 11, in <module>
    sys.exit(main())
  File "/home/fwilhelm/.virtualenvs/venv/lib/python2.7/site-packages/pelican/__init__.py", line 386, in main
    pelican, settings = get_instance(args)
  File "/home/fwilhelm/.virtualenvs/venv/lib/python2.7/site-packages/pelican/__init__.py", line 380, in get_instance
    return cls(settings), settings
  File "/home/fwilhelm/.virtualenvs/venv/lib/python2.7/site-packages/pelican/__init__.py", line 57, in __init__
    self.init_plugins()
  File "/home/fwilhelm/.virtualenvs/venv/lib/python2.7/site-packages/pelican/__init__.py", line 84, in init_plugins
    plugin.register()
AttributeError: 'module' object has no attribute 'register'
```

**Comment by danielfrg** [comment]
You have to change the `pelicanconf.py` to `PLUGINS = ['ipynb.liquid']` instead of `PLUGINS = ['ipynb']`

**Comment by FlorianWilhelm** [comment]
Oh thanks, as described in the README :-)
Hopefully this time I am not asking something obvious but I am still a bit new with Pelican. Now I got:
```
/home/fwilhelm/.virtualenvs/venv/lib/python2.7/site-packages/bs4/__init__.py:166: UserWarning: No parser was explicitly specified, so I'm using the best available HTML parser for this system ("html.parser"). This usually isn't a problem, but if you run this code on another system, or in a different virtual environment, it may use a different parser and behave differently.

To get rid of this warning, change this:

 BeautifulSoup([your markup])

to this:

 BeautifulSoup([your markup], "html.parser")

  markup_type=markup_type))
ERROR: Could not process posts/rbf_networks_with_tensorflow.md
  | TypeError: cannot concatenate 'str' and 'BeautifulSoup' objects
```

So the notebook file is found and read but maybe I need to specify another parser?
