### ISSUE TITLE
 | TypeError: 'bool' object is not callable

### ISSUE THREAD

**Issue by josephcslater** [danielfrg/pelican-ipynb#34]
Unfortunately, I have no idea how to debug this error. The entire log reads:

```
**[jslater@norma josephcslater]$** *make html*
/Users/jslater/Library/Python/3.5/bin/pelican /Users/jslater/websites/josephcslater/content -o /Users/jslater/websites/josephcslater/josephcslater.github.io -s /Users/jslater/websites/josephcslater/pelicanconf.py 
ERROR: Could not process ./SymPy_Multiple_Eqn_solution.ipynb
  | TypeError: 'bool' object is not callable
Done: Processed 6 articles, 5 drafts, 0 pages and 0 hidden pages in 0.98 seconds.
```

I've had to add the .txt extension to these files to be able to upload them.

[SymPy_Multiple_Eqn_solution.ipynb-meta.txt](https://github.com/danielfrg/pelican-ipynb/files/131423/SymPy_Multiple_Eqn_solution.ipynb-meta.txt)
[SymPy_Multiple_Eqn_solution.ipynb.txt](https://github.com/danielfrg/pelican-ipynb/files/131422/SymPy_Multiple_Eqn_solution.ipynb.txt)

**Comment by caseyjlaw** [comment]
FWIW, this is probably an installation issue. I have this problem in one environment, but not in another (all python 2.7). May be worth a fresh install.

**Comment by josephcslater** [comment]
I'm in 3.5. Was in 3.4. Reinstalled pelican. Reinstalled pelican-ipynb. No dice. Tried the demo (with-meta-file). Same error. The install is so trivial, I'm not sure I could be messing it up (bug I've meet that challenge before!). 

This isn't messing my workflow up much, but is in the "would be nice" domain. I am certainly open to being the guinea pig for testing when I have time.  

Noting the installation instruction, I might be able to just workaround as I do serve it off of github. I haven't tried that yet. I know it might end up a time sink... so I need the time to dedicate to a solid try.

**Comment by dionhaefner** [comment]
I was able to track down the error. Running ``make DEBUG=1 html`` gave

> ERROR: Could not process ./hello.ipynb
  | TypeError: 'bool' object is not callable
  |___
  ...
  |   File "./plugins/ipynb/markup.py", line 56, in read
  |     _content, metadata = md_reader.read(metadata_filepath)
  |   File "/usr/local/lib/python2.7/site-packages/pelican/readers.py", line 285, in read
  |     self._md = Markdown(extensions=self.extensions)
  | TypeError: 'bool' object is not callable

Looking at Pelican's ``readers.py``, it said

```python
try:
    from markdown import Markdown
except ImportError:
    Markdown = False  # NOQA
```

Installing the ``markdown`` package via ``pip install markdown`` fixed the error.

**Comment by josephcslater** [comment]
That indeed fixed that error. There is also a dependency on `dateutil` which was easy to figure out from the error. 

Unfortunately: all new error:
ERROR: Could not process ./Laplace_Transforms_Solution.ipynb
  | AttributeError: 'str' object has no attribute 'decode'

I'm looking around, but I have no idea where to look for this. I'm likely missing another dependency.

**Comment by basnijholt** [comment]
I had the same issue, `pip install markdown` also fixed it for me.

**Comment by soedr** [comment]
Ditto on @basnijholt & @dionhaefner's comments.
