### ISSUE TITLE
Exception: Could not find metadata in `.ipynb-meta`, inside `.ipynb` or external `.md` file.

### ISSUE THREAD

**Issue by kskkskksk** [danielfrg/pelican-ipynb#35]
Hello, I got these warnings and error when I ran "sudo make html".

```
WARNING: PLUGIN_PATH setting has been replaced by PLUGIN_PATHS, moving it to the new setting name.
WARNING: Defining PLUGIN_PATHS setting as string has been deprecated (should be a list)
ERROR: Could not process notebook/test.ipynb
  | Exception: Could not find metadata in `.ipynb-meta`, inside `.ipynb` or external `.md` file.
Done: Processed 2 articles, 0 drafts, 0 pages and 0 hidden pages in 0.20 seconds.
```

Here are my settings and environment

- pelican 3.6.3
- jupyter 4.0.6
- nbconvert 4.1.0
- beautifulsoup4 4.4.1

```
content
    notebook
        test.ipynb
        test.ipynb-meta
plugins
    ipynb
        __init__.py
        ...
```

In the pelicanconf.py:
```
...
MARKUP = ('md', 'ipynb')

PLUGIN_PATH = './plugins'
PLUGINS = ['ipynb.markup']
```

I tried to solve the problem but I couldn't. When I write "PLUGIN_PATHS = ['./plugins']" the warnings are gone but still get that error. Any idea? Thank you.

**Comment by kskkskksk** [comment]
Sorry, that was my fault. It looks like I didn't describe ipynb meta data in a proper way.

**Comment by sametmax** [comment]
@ghost I have the same problem so if you could tell me what you did wrong I could fix my code.

**Comment by sametmax** [comment]
Ok I found it. In a .ipynb file there are several "metadata" keys. The one you want is at the very bottom at the file.
