### ISSUE TITLE
Summary contains broken HTML

### ISSUE THREAD

**Issue by dionhaefner** [danielfrg/pelican-ipynb#38]
Summary creation does not work for me. There seem to be multiple issues:
- The summary is created without the notebook CSS, so the cells are not rendered nicely
- More importantly, the summary stops after some `<div>` start tags, without ever closing them, breaking my layout.
- Specifying a summary in the ipynb-meta files is not possible (it is read, but then overridden with the generated summary.

**Comment by philippjfr** [comment]
Any updates on this? Specifying a summary via the ipynb-meta files is still not working for me.

**Comment by fundor333** [comment]
If you use `IPYNB_USE_META_SUMMARY = True` you can't use metadata inside the ipynb

**Comment by danielfrg** [comment]
Yes the idea was to use `IPYNB_USE_META_SUMMARY` to overwrite the generation. 

Yes, in theory that should work. I mainly use the external `md` file but it should work. Please reopen if it doesnt.
