### ISSUE TITLE
Fix for attempting to encode already encoded strings

### ISSUE THREAD

**Issue by FedericoV** [danielfrg/pelican-ipynb#44]
Hi,

Thanks for the awesome plug in.  Yesterday, when trying to push a change to my blog, I noticed an error.  After debugging, what happened was that the plug in was trying to encode strings that were already encoded, and causing a UnicodeEncodeError.

The fix is simple:

[patch.txt](https://github.com/danielfrg/pelican-ipynb/files/248868/patch.txt)

Basically: if there's an encoderror in those lines, it's because it's trying to encode before decoding.

**Comment by danielfrg** [comment]
Added this patch on https://github.com/danielfrg/pelican-ipynb/commit/251b4b9eea0333a60d0a2f152ff86915188784a9
