### ISSUE TITLE
UnicodeDecodeError in markup.py

### ISSUE THREAD

**Issue by ronanpaixao** [danielfrg/pelican-ipynb#54]
There is a bug in `markup.py` handling of Unicode filenames and files.

If I have a non-ASCII character in a filename, I get this error message:

```
ERROR: Could not process <filename>
  | UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 201: ordinal not in range(128)
```

And if I have a non-ASCII character in the contents, I get this:

```
ERROR: Could not process <filename>
  | UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 201: ordinal not in range(128)
```

I have tracked the errors and soon will submit a PR.

**Comment by danielfrg** [comment]
Fixed in #55
