### ISSUE TITLE
ERROR: Could not process .ipynb_checkpoints/first-post-checkpoint.ipynb  

### ISSUE THREAD

**Issue by dipespandey** [danielfrg/pelican-ipynb#58]
ERROR: Could not process .ipynb_checkpoints/first-post-checkpoint.ipynb
  | Exception: Could not find metadata in `.ipynb-meta`, inside `.ipynb` or external `.md` file.

**Comment by jaypeedevlin** [comment]
According to [the readme](https://github.com/danielfrg/pelican-ipynb):

> On the pelicanconf.py you can set:

[a few other things here]

> - `IGNORE_FILES = ['.ipynb_checkpoints']`: prevents pelican from trying to parse notebook checkpoint files
