### ISSUE TITLE
Page Build Failure

### ISSUE THREAD

**Issue by WolfHoward** [danielfrg/pelican-ipynb#62]
I've been getting the following page build failure.

```
The page build failed with the following error:

The submodule registered for `./plugins/ipynb` could not be cloned. Make sure it's using https:// and that it's a public repo. For more information, see https://help.github.com/articles/page-build-failed-invalid-submodule.
```

I've tried publishing from multiple devices and I get the same problem.  
Here's my repo: https://github.com/WolfHoward/WolfHoward.github.io

Any help with this would be greatly appreciated.

**Comment by danielfrg** [comment]
This is more a git issue but I can try to help you. Can you clone your repo with the ` --recursive` flag into a new location:

```
git clone https://github.com/WolfHoward/WolfHoward.github.io --recursive
```

**Comment by WolfHoward** [comment]
Ok. Cloned it to 'plugins2/ipynb'.

________________________________

**Comment by WolfHoward** [comment]
Oh. My repo. Sorry.


________________________________

**Comment by WolfHoward** [comment]
Alright, cloned successfully.
________________________________
