### ISSUE TITLE
something wrong with the &apos escape

### ISSUE THREAD

**Issue by gepcel** [danielfrg/pelican-ipynb#7]
When there are single quote characters in the notebook outputs, nbconvert converts them to "&amp;apos;", which is fine. But the pelican-ipythonnb converts the "&amp;apos;" to "&amp;amp; apos;". 
So the single quote character in the notebook outputs ends up to "&amp;amp; apos;" in the html source code, and "&amp; apos" in the chrome display.

Looks like the single quote is converted twice.
Cannot locate where does the convertion happen.

**Comment by DanceOfDragon** [comment]
Hi， Daniel 

First thanks for creating the great plugin! 
May I know if this issue has been resolved? I followed your recommended method and I also encountered the same problem recently, as shown below: 
![screenshot 2015-09-23 18 19 56](https://cloud.githubusercontent.com/assets/12807684/10042975/ccbbb188-6221-11e5-8d21-eb48055d5408.png)

My setup: 
> Mac OS  X
>Pelican 3.6.0
>iPython notebook 3.2.1
>Python 2,7.10

**Comment by danielfrg** [comment]
Hello, I just tested that example you posted on my setup and it looks to be working in the latest versions. See here: http://danielfrg.com/drafts/ipython-notebook-templates.html

My setup:

```
```

**Comment by DanceOfDragon** [comment]
Hi, thank you very much! 
I turns out to be working fine after I replaced the original plugin with your newest one. 

Another minor issue when generating the HTML file, not sure if you happen to know about it. 
![screenshot 2015-09-24 15 08 14](https://cloud.githubusercontent.com/assets/12807684/10067340/4b73bb04-62ce-11e5-8375-1e7ed032c895.png)

**Comment by FlorianWilhelm** [comment]
@DanceOfDragon @danielfrg Hi, I think this error is not really solved. It only works if `BeautifulSoup4` is not installed. If it is intsalled in `core.get_html_from_filepath` BeautifulSoup starts to mask all ampersands.
