### ISSUE TITLE
BUG: MathJax CDN shutting down on April 30, 2017

### ISSUE THREAD

**Issue by peijunz** [danielfrg/pelican-ipynb#70]
[MathJax CDN shutting down on April 30, 2017](https://www.mathjax.org/cdn-shutting-down/)

Please change the cdn link in [core.py, Line54](https://github.com/danielfrg/pelican-ipynb/blob/master/core.py#L54)
```
mathjaxscript.src = '//cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML';
```
to alternatives like 
```
mathjaxscript.src = '//cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-AMS-MML_HTMLorMML';
```

If necessary, I can make an pull request

**Comment by danielfrg** [comment]
Fixed in #71
