### ISSUE TITLE
Bokeh plots are not working

### ISSUE THREAD

**Issue by eyalshafran** [danielfrg/pelican-ipynb#72]
I have a few Bokeh plots which work on the notebook. When I use the plugin (markup mode - option 1) the plots are just ignored in the output.

I'm not sure if I'm doing something wrong (the plots do work on the notebook), the plugin does not work with Bokeh or if I need to modify something for it to work.

Any ideas?

**Comment by RajeshThallam** [comment]
@eyalshafran, See if the suggestion in the link helps. 
http://pmbaumgartner.github.io/some-tips-for-using-jupyter-notebooks-with-pelican.html

I have not tried myself.

**Comment by eyalshafran** [comment]
Thanks. I'm having some issues with the suggestions made in that link.

I have noticed that if I use the nbconvert to html the Bokeh plots look fine.

**Comment by danielfrg** [comment]
So bokeh plots used to work but I just noticed that my blog (that uses this plugin) is also not rendering them correctly. I'll try to test soon and come back to this. Note that this plugin basically uses `nbconvert` but from python instead of the command.

**Comment by eyalshafran** [comment]
I noticed that if I add:

<head>   
 <link rel="stylesheet" href="https://cdn.pydata.org/bokeh/release/bokeh-0.11.1.min.css" type="text/css" />
         
 <script type="text/javascript" src="https://cdn.pydata.org/bokeh/release/bokeh-0.11.1.min.js"></script>
 <script type="text/javascript">
     Bokeh.set_log_level("info");
 </script>

to the html the Bokeh plots work.

**Comment by jskaza** [comment]
@eyalshafran Where did you add this html code? The article template or after generating the pelican output?

**Comment by danielfrg** [comment]
This was fixed recently. This a test from my blog: http://danielfrg.com/drafts/jupyter-notebook-test.html

Please reopen with an example if not working.

**Comment by eyalshafran** [comment]
@danielfrg I still could not get it to work. Can you please specify what you mean by "reopen with example"?
