### ISSUE TITLE
pelican-ipynb fails to build when pushing to master 

### ISSUE THREAD

**Issue by johnmwood** [danielfrg/pelican-ipynb#78]
The page build failed for the `master` branch with the following error:

The submodule registered for `./plugins/ipynb` could not be cloned. Make sure it's using https:// and that it's a public repo. For more information, see https://help.github.com/articles/page-build-failed-invalid-submodule/.

**Comment by danielfrg** [comment]
Yes, as yn-coder says try cloning it with `--recursive`
