### ISSUE TITLE
Use outside of pelican

### ISSUE THREAD

**Issue by wassimseif** [danielfrg/pelican-ipynb#81]
First of all, Thank you for the awesome plugin.
I was wondering if this can be used with a blog not using pelican. Just using the plugins to general HTML from a notebook & using them in another website ?

**Comment by danielfrg** [comment]
You can generate HTML from the notebook using [jupyter nbconvert](https://github.com/jupyter/nbconvert). This will generate html and css that you can just serve.

Closing as not issue but feel free to ask other questions
