### ISSUE TITLE
Plotly Chart Does Not Show Up

### ISSUE THREAD

**Issue by guramera** [danielfrg/pelican-ipynb#95]
Hello, I'm having an issue where I use pyplot in my notebook but the ouput shows nothing after I deploy the post 
![blankpyploy](https://user-images.githubusercontent.com/19705389/42994905-a004e5de-8c39-11e8-9f89-92eedd3e93c7.PNG)

My blog post can be found here https://guramera.github.io/notebook-3.html#notebook-3

The code works properly on my kaggle though 
![kaggleplot](https://user-images.githubusercontent.com/19705389/42995263-9d7ffd98-8c3a-11e8-8909-09b07d07c7b5.PNG)

Is there anything I can do to solve this problem? Thank you very much for your help

**Comment by danielfrg** [comment]
For plotly to work you need to add [requirejs](https://requirejs.org/) to the page of the post. It usually just easy to drop the script tag on your theme.

**Comment by guramera** [comment]
That works perfectly,thank you very much!!
